@Library('jenkins-shared-library') _

pipeline {
    agent any

   parameters {
        string defaultValue: 'main-v2', name: 'branchName'
    }

    environment {

        IMAGE_NAME = 'gcr.io/opsdev-org/status-fe'
        VALUE_FILE = 'frontend/values.yaml'
        HELM_DEP_NAME = 'status-fe'
        IMAGE = 'status-fe'
        CREDENTIAL_ID = 'gke-jenkins'
        REPO = 'frontend'
    }

    stages {


        stage('Build and Deploy') {
            steps {

                script {
                  
                    dockerHelmTask.call(env.CREDENTIAL_ID,env.IMAGE_NAME,env.VALUE_FILE,env.HELM_DEP_NAME,env.REPO)
                }

            }
        }

    }
}