service:
  name: status-fe-service
  port: 3000
  replicas: 1
  type: ClusterIP

image:
  repository: gcr.io/opsdev-org/status-fe
  tag: latest
  pullPolicy: Always

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

existingSecret: "" # Set to "statuspage-frontend-secrets" if you want to mount the frontend secret file

env:
  NEXT_PUBLIC_API_URL: "https://api.status.opsdev.in"
  NEXT_PUBLIC_WS_URL: "wss://api.status.opsdev.in"
  NEXT_PUBLIC_APP_URL: "https://status.opsdev.in"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
