@Library('jenkins-shared-library') _

pipeline {
    agent any

   parameters {
        string defaultValue: 'main-v2', name: 'branchName'
        string defaultValue: "kuberenetes", name: 'clusterName'
        string defaultValue: "us-central1-a", name: 'clusterZone'
    }
    environment {

        REGISTRY = 'gcr.io/opsdev-org'
        VALUE_FILE = 'backend/values.yaml'
        CREDENTIAL_ID = 'gke-jenkins'
        REPO = 'backend'
    }

    stages {


        stage('Build and Deploy') {
            steps {

                script {
                  
                    dockerHelmTask.call(env.CREDENTIAL_ID,env.REGISTRY,env.VALUE_FILE,env.JOB_NAME,env.REPO, params.clusterName,params.clusterZone)
                }

            }
        }

    }
}