@Library('jenkins-shared-library') _

pipeline {
    agent any

   parameters {
        string defaultValue: 'main-v2', name: 'branchName'
        string defaultValue: "k8s", name: 'clusterName'
    }
    environment {

        IMAGE_NAME = 'gcr.io/opsdev-org/status-be'
        VALUE_FILE = 'backend/values.yaml'
        HELM_DEP_NAME = 'status-be'
        IMAGE = 'status-be'
        CREDENTIAL_ID = 'gke-jenkins'
        REPO = 'backend'
    }

    stages {


        stage('Build and Deploy') {
            steps {

                script {
                  
                    dockerHelmTask.call(env.CREDENTIAL_ID,env.IMAGE_NAME,env.VALUE_FILE,env.HELM_DEP_NAME,env.REPO, params.clusterName)
                }

            }
        }

    }
}