sonar.projectKey=statuspage-monitor
sonar.projectName=statuspage-monitor

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
# sonar.externalIssuesReportPaths=custom_analysis_report.json