service:
  name: status-be-service
  port: 8000
  replicas: 1
  type: ClusterIP

image:
  repository: gcr.io/opsdev-org/status-be
  tag: latest
  pullPolicy: Always

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

existingSecret: "statuspage-backend-secrets"

env:
  DATABASE_URL: ""
  REDIS_URL: ""
  USE_NEON_DB: "true"
  USE_CLOUD_REDIS: "true"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
  FROM_EMAIL: "no-reply@status.opsdev.in"
  FRONTEND_URL: "https://status.opsdev.in"
  EXPECTED_CNAME_TARGET: "status.opsdev.in"

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
