"""add email otp fields to tenant

Revision ID: 2b3c4d5e6f7a
Revises: 1a2b3c4d5e6f
Create Date: 2026-03-28 02:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b3c4d5e6f7a'
down_revision: Union[str, None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('is_email_verified', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('tenants', sa.Column('email_otp', sa.String(length=6), nullable=True))
    op.add_column('tenants', sa.Column('email_otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'email_otp_expires_at')
    op.drop_column('tenants', 'email_otp')
    op.drop_column('tenants', 'is_email_verified')
    # ### end Alembic commands ###
