name: Ephemeral PR Environment (GCP UAT)

on:
  pull_request:
    branches:
      - stage
    types: [opened, synchronize, closed]
  
env:
  TF_WORKSPACE: "PR-${{ github.event.pull_request.number }}"

jobs:
  provision-infra:
    name: Provision GCP Infra
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform-repo/environments/stage

    steps:
      - name: Checkout App Code
        uses: actions/checkout@v4

      - name: Checkout Terraform IaC Code
        uses: actions/checkout@v4
        with:
          repository: saeed5077/Terraform-IaaC
          token: ${{ secrets.GH_PAT }} 
          path: terraform-repo

      # - name: Debug structure
      #   run: ls -R      

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
   
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform-repo/environments/stage

      # - name: Terraform Workspace Select or New
      #   run: terraform workspace select ${{ env.TF_WORKSPACE }} || terraform workspace new ${{ env.TF_WORKSPACE }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_env: "pr-${{ github.event.pull_request.number }}"

  deploy-services:
    name: Deploy FE & BE
    needs: provision-infra
    runs-on: ubuntu-latest

    strategy:
      matrix:
        job: [status-be, status-fe]

    steps:
      - name: Trigger Jenkins Pipeline for App Deployment
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/${{ matrix.job }}/buildWithParameters" \
          --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
          --max-time 60 \
          --data-urlencode "branchName=${{ github.head_ref }}" \
          --data-urlencode "clusterName=pr-${{ github.event.pull_request.number }}" \
          --data-urlencode "clusterZone=us-central1-a"

  teardown:
    name: Destroy GCP Infrastructure
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./terraform-repo/environments/stage

    steps:
      - name: Checkout Terraform IaC Code
        uses: actions/checkout@v4
        with:
          repository: saeed5077/Terraform-IaaC
          token: ${{ secrets.GH_PAT }}
          path: terraform-repo

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: |
          # terraform workspace select ${{ env.TF_WORKSPACE }}
          terraform destroy -auto-approve
          terraform workspace select default
          # terraform workspace delete ${{ env.TF_WORKSPACE }}
        env:
          TF_VAR_env: "pr-${{ github.event.pull_request.number }}"